baseURL = 'https://github.com/MJShinpain/classic_schedule.git'
languageCode = "ko-KR"
title = "í´ë˜ì‹ ê³µì—° ì¼ì •"
theme = [ "PaperMod" ]
sectionPagesMenu = "main"
paginate = 10
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
dataDir = "data"
googleAnalytics = "UA-123-45"

[outputs]
home = [ "HTML", "JSON" ]

[minify]
disableXML = true
minifyOutput = true

[params]
env = "production"
title = "í´ë˜ì‹ ê³µì—° ì¼ì •"
description = "í´ë˜ì‹ ê³µì—° ì¼ì •ì„ ì •ë¦¬í•´ì„œ ë³´ì—¬ë“œë¦½ë‹ˆë‹¤."
keywords = [ "Blog", "Portfolio", "í´ë˜ì‹ ê³µì—°" ]
author = "Me"
DateFormat = "January 2, 2006"
defaultTheme = "auto"
disableThemeToggle = true
ShowReadingTime = false
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = false
ShowWordCount = false
ShowRssButtonInSectionTermList = true
UseHugoToc = true
disableSpecial1stPost = false
disableScrollToTop = false
comments = false
hidemeta = false
hideSummary = true
showtoc = false
tocopen = false

  [params.assets]
  favicon = "<link / abs url>"
  favicon16x16 = "<link / abs url>"
  favicon32x32 = "<link / abs url>"
  apple_touch_icon = "<link / abs url>"
  safari_pinned_tab = "<link / abs url>"

  [params.label]
  text = "í´ë˜ì‹ ê³µì—° ì¼ì •"
  icon = "/images/music.png"
  iconHeight = 35

  [params.profileMode]
  enabled = true
  title = "í´ë˜ì‹ ê³µì—° ì¼ì •"
  subtitle = "í´ë˜ì‹ ê³µì—° ì¼ì •ì„ ëª¨ì•„ë‘ì—ˆìŠµë‹ˆë‹¤. ì œê°€ ë³´ë ¤ê³ ."
  imageUrl = "images/logo.jpg"
  imageWidth = 120
  imageHeight = 120
  imageTitle = "my image"

    [[params.profileMode.buttons]]
    name = "ì˜ˆìˆ ì˜ ì „ë‹¹"
    url = "sac"

    [[params.profileMode.buttons]]
    name = "ì„¸ì¢…ë¬¸í™”íšŒê´€"
    url = "pages"

  [params.homeInfoParams]
  Title = "í´ë˜ì‹ ê³µì—° ì¼ì • ğŸ‘‹"
  Content = "í´ë˜ì‹ ê³µì—° ì¼ì •ì„ ëª¨ì•„ë‘ì—ˆìŠµë‹ˆë‹¤."

  [[params.socialIcons]]
  name = "x"
  url = "https://x.com/"

  [[params.socialIcons]]
  name = "stackoverflow"
  url = "https://stackoverflow.com"

  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/"

[params.analytics.google]
SiteVerificationTag = "XYZabc"

[params.analytics.bing]
SiteVerificationTag = "XYZabc"

[params.analytics.yandex]
SiteVerificationTag = "XYZabc"

  [params.cover]
  hidden = true
  hiddenInList = true
  hiddenInSingle = false

  [params.editPost]
  URL = ""
  Text = ""
  appendFilePath = true

  [params.fuseOpts]
  isCaseSensitive = false
  shouldSort = true
  location = 0
  distance = 1_000
  threshold = 0.4
  minMatchCharLength = 0
  limit = 10
  keys = [ "title", "permalink", "summary", "content" ]

[[menu.main]]
identifier = "pages"
name = "ì„¸ì¢…ë¬¸í™”íšŒê´€"
url = "/pages/"
weight = 2

[[menu.main]]
identifier = "ì˜ˆìˆ ì˜ ì „ë‹¹"
name = "ì˜ˆìˆ ì˜ ì „ë‹¹"
url = "/sac/"
weight = 1

[[menu.main]]
name = "ê²€ìƒ‰"
url = "search/"
weight = 3
